env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:nuxt/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  vue/no-multiple-template-root: off
